spring:
  datasource:
    url: jdbc:mysql://localhost:3306/omarket?serverTimezone=UTC&useLegacyDatetimeCode=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    session:
      host:
      port:
      password:
    cache:
      host:
      port:
      password:

mybatis:
  type-aliases-package: com.omarket.*.domain
  mapper-locations: mybatis/mapper/**/*.xml

ncp:
  object-storage:
    end-point:
    region-name:
    access-key:
    secret-key:
    bucket-name: